export 'nav_screen.dart';
export 'patient/patient.dart';
export 'review.dart';
export 'notification.dart';
export 'settings.dart';
export 'setting_pin_clinic.dart';
export 'signup_login.dart';
export 'verify_otp.dart';
export 'splash_screen.dart';
export 'error_place_holder.dart';
export 'place_holder.dart';
export 'app_start_splash.dart';
export 'about_us.dart';
export 'error_place_holder_page.dart';
export 'forget_password.dart';
export 'loading_place_holder.dart';
// export 'about_us_temp/about_us.dart';
// doctor
export 'doctor/profile_setting.dart';
export 'doctor/basic_info_setting.dart';
export 'doctor/about_me_setting.dart';
export 'doctor/clinic_info_setting.dart';
export 'doctor/education_setting.dart';
export 'doctor/experience_setting.dart';
export 'doctor/care_service_setting.dart';
export 'doctor/award_setting.dart';
export 'doctor/temp/view_doctor_profile_temp1.dart';
export 'doctor/temp/view_care_service.dart';
export 'doctor/temp/view_clinic_info.dart';
export 'doctor/temp/view_education.dart';
export 'doctor/temp/view_experience.dart';
export 'doctor/view_doctor_profile.dart';
export 'doctor/change_password.dart';
export 'doctor/doctor_more_info.dart';
export 'doctor/profile_submission.dart';
// patient
export 'patient/patient_profile.dart';
export 'patient/overview_tab_patient.dart';
export 'patient/patient_appt_slot.dart';
export 'patient/medical_record.dart';
// export 'temp/patient_list.dart';

// appt
export 'appt/appt_list.dart';
export 'appt/appointment.dart';
export 'appt/clinic_booked_appt.dart';
export 'appt/doctor_appt_slot_list.dart';
export 'appt/clinic_map_location.dart';
export 'appt/schedule_clinic_appt.dart';
export 'appt/schedule.dart';
export 'appt/clinic_booked_appt_list.dart';
export 'appt/view_week_day_appt_list.dart';
export 'appt/appt_summary.dart';

// chat
export 'chat/chat_list.dart';
export 'chat/chat_message.dart';
